version: '3.4'

services:
  postgres:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbPassword123
      - POSTGRES_DB=app
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

